[project]
name = "printer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "escpos>=2.0.0",
    "image>=1.5.33",
    "numpy>=2.3.1",
    "watchdog>=6.0.0",
]
